version: '3.3'
services:
  crawler: 
    build: .
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./crawler:/app/crawler
      - ./scrapy.cfg:/app/scrapy.cfg
      - ./data:/app/data
